package com.example.mylistapplication;

import java.util.ArrayList;

public class ListItem {
    public static String[][] data = new String[][]{
            {"Papua (777.000 Km²)", "Pulau ini dibagi menjadi dua wilayah yang bagian baratnya dikuasai oleh Indonesia dan bagian timurnya merupakan negara Papua Nugini. pulau ini terletak pada koordinat 5°20′S 141°36′E. Istilah “Papua” digunakan untuk merujuk kepada pulau ini secara keseluruhan. Nugini berasal dari kata New Guinea, nama yang diberikan oleh orang Barat, yang di-Indonesiakan. Mereka dahulu berpendapat bahwa tanah Papua mirip Guinea, sebuah wilayah di Afrika. Jadi mereka sebut Guinea baru. \n\nIstilah “Papua” sekarang juga digunakan untuk merujuk kepada provinsi di Papua bagian barat yang dikuasai oleh Indonesia, yaitu Papua dan Papua Barat. Di pulau ini terletak gunung tertinggi di Indonesia, yaitu Puncak Jaya (5.030 m).", "https://upload.wikimedia.org/wikipedia/commons/b/b6/New_Guinea_Topography.png","5°20′S 141°36′E","11 juta jiwa (2014)","Jayapura"},
            {"Kalimantan (743.330 Km²)", "Kalimantan adalah sebuah pulau yang terletak di sebelah utara Pulau Jawa dan di sebelah Barat Pulau Sulawesi. Terbagi menjadi wilayah Brunei, Indonesia dan Malaysia. Pulau ini terletak pada koordinat 1°00′ LU 114°00′ BT Seringkali pulau ini secara keseluruhan disebut Borneo sedangkan wilayah Indonesia disebut Kalimantan, lalu wilayah Malaysia disebut Sarawak dan Sabah. Selain itu ada pula kesultanan Brunei. \n\nPada zaman dahulu, Borneo adalah nama yang dipakai oleh kolonial Inggris dan Belanda, sedangkan nama pulau Kalimantan digunakan oleh penduduk Indonesia. Dalam bahasa Indonesia dahulu, Kalimantan Utara adalah sebutan untuk Borneo Utara (Sabah), tetapi dalam pengertian sekarang Kalimantan Utara adalah Kalimantan Timur bagian utara. Jadi dalam arti luas Kalimantan meliputi seluruh pulau Borneo, sedangkan dalam arti sempit Kalimantan hanya mengacu pada wilayah Indonesia. Pada pulau ini terdapat 4 Provinsi yaitu: Kalimantan Barat, Kalimantan Tengah, Kalimantan Selatan, Kalimantan Timur. ", "https://upload.wikimedia.org/wikipedia/commons/f/f2/Borneo2_map_english_names.PNG","1°00′N 114°00′E","21 juta jiwa (2014)","Samarinda"},
            {"Sumatra (425.000 Km²)", "Pulau ini terletak pada koordinat 0°00′ LU 102°00′ BT. Terdapat 8 Provinsi yaitu: Aceh, Sumatra Utara, Riau, Jambi, Bengkulu, Sumatra Barat, Sumatra Selatan, dan Lampung.   Penduduk pulau ini sekitar 58 Juta jiwa (2018). Di Sumatera pernah terdapat kerajaan Samudera (sekarang Aceh). \n\nKonon pada kunjungannya ke pulau tersebut Ibnu Batutah (cendekiawan Islam asal Maroko) selalu melafalkan kata Samudera menjadi Sumatera, semenjak saat itu nama Sumatera dikenal luas sebagai nama pulau tersebut. Selain dikenal dengan nama Sumatra, pulau tersebut dikenal dengan nama pulau Andalas atau pula Suwarnadwipa. Suwarnadwipa artinya ialah “pulau emas”. Naskah Negarakertagama dari abad ke-14 menyebut “Bumi Malayu” untuk pulau ini. Puncak tertinggi adalah gunung Kerinci 3.805m.", "https://upload.wikimedia.org/wikipedia/commons/0/06/Sumatra_Topography.png","0°00′N 102°00′E","58 juta jiwa (2018)","Medan"},
            {"Sulawesi (174.600Km²)", "Pulau ini terletak pada Koordinat 2°08′ LS 120°17′ BT. Pulau ini terdapat 8 Provinsi yaitu: Gorontalo, Sulawesi Utara, Sulawesi barat, Sulawesi Tengah, Sulawesi Tenggara, Sulawesi Selatan. Dengan Puncak tertinggi adalah gunung Rantemario 3,478 m. Bentang alam di Sulawesi mencakup empat semenanjung: Semenanjung Minahasa di bagian utara; Semenanjung Timur; Semenanjung Selatan; dan Semenanjung Tenggara.", "https://upload.wikimedia.org/wikipedia/commons/6/65/Sulawesi_Topography.png","02°S 121°E","18 juta jiwa (tahun 2014)","Makassar"},
            {"Jawa (126.700 Km²)", "Pulau ini terletak pada Koordinat 7°30′10″LS,111°15′47″BT. Pulau ini merupakan pulau dengan jumlah penduduk terpadat di Indonesia dengan penduduk sekitar 124 juta jiwa. Terdapat 6 Provinsi yaitu: DKI Jakarta, Banten, Jawa Barat, Jawa Tengah, Daerah Istimewa Yogyakarta, dan Jawa Timur. Puncak tertingginya adalah Gunung Semeru 3.676 meter gunung ini terletak diantara wilayah administrasi Kabupaten Malang dan Lumajang, dengan posisi geografis antara 8°06′ LS dan 120°55′ BT. ", "https://upload.wikimedia.org/wikipedia/commons/4/43/Java_Topography.png","7°30′10″LS,111°15′47″BT.","160.293.748 jiwa (2015)","DKI Jakarta"},
            {"Timor (30.777 Km²)", "Timor adalah sebuah pulau di bagian selatan Nusantara, terbagi antara negara merdeka Timor Leste dan kawasan Timor Barat, bagian dari provinsi Nusa Tenggara Timur di Indonesia. Luas Pulau Timor sekitar 30.777 km². Nama pulau ini diambil dari kata ‘timur’, bahasa Melayu untuk “timur”; dinamakan demikian karena dia terletak di ujung timur rantai kepulauan.", "https://upload.wikimedia.org/wikipedia/commons/f/fd/Timor.png","-9° 13' 60.00' S","3,183 juta (2014)","Kupang (Indonesia)"},
            {"Halmahera (17.780 km²)", "Halmahera (juga Jilolo atau Gilolo) adalah pulau terbesar di Kepulauan Maluku, terletak pada koordinat 0°36′ LU 127°52′ BT. Pulau ini merupakan bagian dari provinsi Maluku Utara, Indonesia. Halmahera memilik luas tanah 17.780 km² (6.865 mil persegi) dan populasi 1995 sekitar 162.728. Pada 1997, sekitar 80% penduduk adalah Muslim, dan sekitar 20% adalah Kristen.Pulau ini dibagi menjadi 5 kabupaten: Kabupaten Halmahera Timur, Kabupaten Halmahera Selatan, Kabupaten Halmahera Barat, Kabupaten Halmahera Utara, dan Kabupaten Halmahera Tengah.", "https://upload.wikimedia.org/wikipedia/commons/8/80/Halmahera_Topography.png","0°36′N 127°52′E","162.728 jiwa (Tahun ?)","Sofifi"},
            {"Seram (17.200 Km²)", "Pulau Seram terletak di sebelah utara Pulau Ambon, Provinsi Maluku, Indonesia. Kota utamanya ialah Masohi, ibukota kabupaten Maluku Tengah. Di pulau ini terdapat beberapa pelabuhan: Amahai, Masohi, Kairatu, dan pelabuhan rakyat seperti Tehoru, Bula, Geser, dan Piru. Pulau Seram memiliki alam pegunungan dan hutan tropis. Produk-produk yang dihasilkan antara lain cengkih, pala, kopra, damar, sagu, ikan, dan minyak. \n\nTerdapat satu taman nasional yaitu Taman Nasional Manusela yang terkenal karena banyak hewan dan tumbuhan endemiknya. Untuk mencapai tempat ini dapat ditempuh melalui Desa Yaputih atau Hatu di Kecamatan Tehoru, kurang lebih 100km dari Masohi.", "https://upload.wikimedia.org/wikipedia/commons/9/9d/Seram_en.png"," 3°19'42\"S   129°15'58\"E","285.006 jiwa","Dataran Hunipopu"},
            {"Flores (14.300 km²)", "Flores, dari bahasa Portugis yang berarti “bunga” berada di Provinsi Nusa Tenggara Timur, Indonesia. Flores termasuk dalam gugusan Kepulauan Sunda Kecil bersama Bali dan NTB, dengan luas wilayah sekitar 14.300 km². Pulau Flores bersama Pulau Timor, Pulau Sumba dan Kepulauan Alor merupakan empat pulau besar di Provinsi NTT yang merupakan salah satu provinsi kepulauan di Indonesia dengan 566 pulau. \n\nDi ujung barat dan timur Pulau Flores ada beberapa gugusan pulau kecil. Di sebelah timur ada gugusan Pulau Lembata, Adonara dan Solor, sedangkan di sebelah barat ada gugusan Pulau Komodo dan Rinca. Sebelah barat pulau Flores, setelah gugusan pulau-pulau kecil itu ada pulau Sumbawa (NTB), sedangkan di sebelah timur setelah gugusan pulau-pulau kecil itu ada kepulauan Alor.Di sebelah tenggara ada pulau Timor. Di sebelah barat daya ada pulau Sumba, di sebelah selatan ada laut Sawu, sebelah utara, di seberang Laut Flores ada Sulawesi.", "https://upload.wikimedia.org/wikipedia/commons/6/65/Flores_Topography.png","8°40′29″S 121°23′04″E","2 juta jiwa (2010)","Maumere"},
            {"Sumbawa (13.400 Km²)", "Pulau Sumbawa adalah sebuah pulau yang terletak di provinsi Nusa Tenggara Barat, Indonesia . Terletak pada koordinat 8°47′ LS 118°5′ BT. \n\nPulau ini dibatasi oleh Selat Alas di sebelah barat (memisalahkan dengan Pulau Lombok), Selat Sape di sebelah timur (memisahkan dengan Pulau Komodo), Samudra Hindia di sebelah selatan, serta Laut Flores di sebelah utara. Kota terbesarnya adalah Bima, yang berada di bagian timur pulau ini. Pulau ini memiliki luas 13.400 km2, dan merupakan pulau terbesar di provinsi Nusa Tenggara Barat, serta salah satu dari dua pulau utama di provinsi tersebut. Titik tertingginya adalah Gunung Tambora (2.824 m), yang juga merupakan gunung api aktif.", "https://upload.wikimedia.org/wikipedia/commons/8/8c/Soembawa_kaart.jpg","8°47′S 118°5′E","4 juta jiwa (2005)","Bima"},
    };


    public static ArrayList<Item> getListData(){
        ArrayList<Item> list = new ArrayList<>();
        for (String[] aData : data){
            Item item = new Item();
            item.setNama(aData[0]);
            item.setDesc(aData[1]);
            item.setPhoto(aData[2]);
            item.setCoordinates(aData[3]);
            item.setPopulation(aData[4]);
            item.setCity(aData[5]);
            list.add(item);
        }

        return list;

    }

}

